apiVersion: v1
kind: Service
metadata:
  name: nginx-devops-service
spec:
  selector:
    app: nginx-devops
  ports:
  - protocol: TCP
    port: 80        # porta interna do Service
    targetPort: 80  # porta do container
    name: web   # 🔑 Prometheus usa isto
  type: NodePort    # podes usar LoadBalancer se tiveres cloud (AWS, GCP, Azure)
