name: CI/CD Pipeline

on:
  push:
    branches: [ "dev-joao" ]

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Login no DockerHub
        run: docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_PASSWORD }}"

      - name: Build da imagem
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/nginx-devops-projeto:latest .

      - name: Push para DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/nginx-devops-projeto:latest
